package com.situ.aichat.moments

import com.situ.aichat.data.local.entity.MomentPostEntity
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * [MomentNewPostNotificationPlanner] 纯函数单测（13.7e）。断言反推自既定「保守节流」规则（用户拍板）：
 * 每角色每天≤1（排除已推过的角色）、同角色一轮多帖只取一条、0/1/≥2 角色 → None/Single/Merged。
 */
class MomentNewPostNotificationPlannerTest {

    private fun post(uuid: String, charUuid: String?): MomentPostEntity =
        MomentPostEntity(uuid = uuid, characterUuid = charUuid, authorTypeRaw = "character", isAutoGenerated = true)

    @Test
    fun emptyRun_isNone() {
        assertEquals(MomentNewPostNotificationPlanner.Plan.None, MomentNewPostNotificationPlanner.plan(emptyList(), emptySet()))
    }

    @Test
    fun singleCharacter_notThrottled_isSingle() {
        val p = post("p1", "c1")
        val plan = MomentNewPostNotificationPlanner.plan(listOf(p), emptySet())
        assertTrue(plan is MomentNewPostNotificationPlanner.Plan.Single)
        assertEquals(p, (plan as MomentNewPostNotificationPlanner.Plan.Single).post)
    }

    @Test
    fun singleCharacter_alreadyNotifiedToday_isNone() {
        val plan = MomentNewPostNotificationPlanner.plan(listOf(post("p1", "c1")), setOf("c1"))
        assertEquals(MomentNewPostNotificationPlanner.Plan.None, plan)
    }

    @Test
    fun twoCharacters_sameRun_isMergedOfTwo() {
        val plan = MomentNewPostNotificationPlanner.plan(listOf(post("p1", "c1"), post("p2", "c2")), emptySet())
        assertTrue(plan is MomentNewPostNotificationPlanner.Plan.Merged)
        assertEquals(2, (plan as MomentNewPostNotificationPlanner.Plan.Merged).posts.size)
    }

    @Test
    fun threeCharacters_oneThrottled_mergesRemainingTwo() {
        val posts = listOf(post("p1", "c1"), post("p2", "c2"), post("p3", "c3"))
        val plan = MomentNewPostNotificationPlanner.plan(posts, setOf("c2"))
        assertTrue(plan is MomentNewPostNotificationPlanner.Plan.Merged)
        val merged = plan as MomentNewPostNotificationPlanner.Plan.Merged
        assertEquals(2, merged.posts.size)
        assertTrue(merged.posts.none { it.characterUuid == "c2" })
    }

    @Test
    fun twoCharacters_oneThrottled_collapsesToSingle() {
        val plan = MomentNewPostNotificationPlanner.plan(listOf(post("p1", "c1"), post("p2", "c2")), setOf("c1"))
        assertTrue(plan is MomentNewPostNotificationPlanner.Plan.Single)
        assertEquals("c2", (plan as MomentNewPostNotificationPlanner.Plan.Single).post.characterUuid)
    }

    @Test
    fun sameCharacterTwice_oneRun_dedupesToSingle() {
        // 防御：一轮里同角色万一两帖，只取第一条（实际每角色一轮至多一帖）。
        val plan = MomentNewPostNotificationPlanner.plan(listOf(post("p1", "c1"), post("p2", "c1")), emptySet())
        assertTrue(plan is MomentNewPostNotificationPlanner.Plan.Single)
        assertEquals("p1", (plan as MomentNewPostNotificationPlanner.Plan.Single).post.uuid)
    }

    @Test
    fun nullCharacterUuid_excluded() {
        // 用户帖 / 异常帖无 characterUuid → 不推（仅角色帖才推「X 发了新动态」）。
        val plan = MomentNewPostNotificationPlanner.plan(listOf(post("p1", null)), emptySet())
        assertEquals(MomentNewPostNotificationPlanner.Plan.None, plan)
    }
}
