package com.situ.aichat.ui.moments

import android.content.Context
import android.net.Uri
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.situ.aichat.data.local.dao.UserProfileDao
import com.situ.aichat.data.local.entity.MomentPostEntity
import com.situ.aichat.data.local.entity.UserProfileEntity
import com.situ.aichat.data.model.MomentAuthorType
import com.situ.aichat.data.repository.MomentRepository
import com.situ.aichat.data.repository.SettingsRepository
import com.situ.aichat.moments.MomentInteractionService
import com.situ.aichat.util.ContentImageStore
import com.situ.aichat.util.StringListJson
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject

/** 发布页编辑状态。[images]=已落盘的磁盘路径；[publishing] 防重复发布。 */
data class ComposeMomentState(
    val content: String = "",
    val images: List<String> = emptyList(),
    val publishing: Boolean = false,
)

/**
 * 朋友圈发布 VM（M06 7.2.7，对齐 iOS `ComposeMomentView`）：500 字正文 + ≤9 图。发布 → 落 [MomentPostEntity]
 * (authorType=user) → 调 [MomentInteractionService.scheduleAIInteraction]（延迟 = `momentCommentDelay`，
 * 对齐 iOS publishPost）触发 AI 角色延迟点赞/评论。
 *
 * 图片即选即落盘（`ContentImageStore`，已缩到 1024px）；本会话落盘但最终未发布的（放弃 / 移除后未发）作为
 * 孤儿在放弃 / 发布清理 / [onCleared] 安全网中删除。无编辑模式（发布是一次性的）。
 */
@HiltViewModel
class ComposeMomentViewModel @Inject constructor(
    @ApplicationContext private val context: Context,
    private val momentRepo: MomentRepository,
    private val settingsRepo: SettingsRepository,
    private val interactionService: MomentInteractionService,
    userProfileDao: UserProfileDao,
) : ViewModel() {

    private val _state = MutableStateFlow(ComposeMomentState())
    val state: StateFlow<ComposeMomentState> = _state.asStateFlow()

    val userProfile: StateFlow<UserProfileEntity?> =
        userProfileDao.observe().stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), null)

    /** 本次会话经 picker 落盘的路径（用于孤儿清理）。 */
    private val sessionSavedPaths = mutableSetOf<String>()

    fun setContent(value: String) {
        _state.value = _state.value.copy(content = value)
    }

    /** 选图后落盘并追加（总数钳到 9，对齐 iOS `maxSelectionCount:9`）。 */
    fun addImages(uris: List<Uri>) {
        if (uris.isEmpty()) return
        viewModelScope.launch {
            val saved = ContentImageStore.saveAll(context, uris)
            sessionSavedPaths.addAll(saved)
            _state.value = _state.value.copy(images = (_state.value.images + saved).take(MAX_IMAGES))
        }
    }

    /** 从列表移除（删盘推迟到发布/放弃统一处理，避免主线程文件 IO）。 */
    fun removeImage(path: String) {
        _state.value = _state.value.copy(images = _state.value.images - path)
    }

    val hasUnsavedChanges: Boolean
        get() = _state.value.content.isNotBlank() || _state.value.images.isNotEmpty()

    /**
     * 发布（对齐 iOS `publishPost`）：trim 正文 → 落 user 帖 → 排 AI 延迟互动（`momentCommentDelay`）→ onDone。
     * 空正文 / 超长 / 正在发布时不动。
     */
    fun publish(onDone: () -> Unit) {
        val s = _state.value
        val content = s.content.trim()
        if (content.isEmpty() || s.content.length > MAX_CHARS || s.publishing) return
        viewModelScope.launch {
            _state.value = s.copy(publishing = true)
            val uuid = UUID.randomUUID().toString()
            momentRepo.upsert(
                MomentPostEntity(
                    uuid = uuid,
                    content = content,
                    timestamp = System.currentTimeMillis(),
                    authorTypeRaw = MomentAuthorType.USER.raw,
                    characterUuid = null,
                    isAutoGenerated = false,
                    imagePathsJson = StringListJson.encode(s.images),
                )
            )
            val delayMinutes = settingsRepo.getAppSettings().momentCommentDelay
            interactionService.scheduleAIInteraction(uuid, delayMinutes)
            // 已发布的图归该帖所有；删除本会话落盘但未进帖的孤儿（移除过的）。
            val finalSet = s.images.toSet()
            ContentImageStore.delete(sessionSavedPaths.filter { it !in finalSet })
            sessionSavedPaths.clear()
            onDone()
        }
    }

    /** 放弃：删除本次会话落盘的全部孤儿图（未发布，无 DB 引用）。 */
    fun discard() {
        ContentImageStore.delete(sessionSavedPaths.toList())
        sessionSavedPaths.clear()
    }

    /** 安全网：未发布即离开（系统返回 / 进程回收）时清理本会话孤儿图。 */
    override fun onCleared() {
        if (sessionSavedPaths.isNotEmpty()) {
            ContentImageStore.delete(sessionSavedPaths.toList())
            sessionSavedPaths.clear()
        }
    }

    companion object {
        const val MAX_CHARS = 500
        const val MAX_IMAGES = 9
    }
}
