package com.situ.aichat.data.local.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Mirrors the iOS `DiaryEntry` @Model (Models/DiaryEntry.swift). The user-perspective diary book
 * (M07): user-written, AI-assisted, or auto-generated entries, plus pet diaries (P8) sharing this
 * table via [isPetDiary].
 *
 * Storage notes (Android adaptations):
 * - Images: iOS `imageDataArray: [Data]?` external storage → here JPEGs on disk via
 *   `ContentImageStore`, with their paths kept as a JSON list in [imagePathsJson] (decode via
 *   `DiaryEntryEntity.imagePaths`). No BLOBs in the DB.
 * - Enums (`visibilityRaw` / `triggerTypeRaw`) store the iOS rawValue strings; decode via
 *   [com.situ.aichat.data.model.DiaryVisibility] / [com.situ.aichat.data.model.MomentTriggerType].
 * - `weatherText` is intentionally OMITTED — it is a dead field in iOS (declared but never written
 *   or read; verified against source). Re-add only if a real feature needs it.
 *
 * [triggerTypeRaw] / [relatedGiftId] are kept so the gift branch (P9) drops in without a migration;
 * [isPetDiary] / [petSpeciesRaw] likewise for the pet diary (P8). Deleting an entry cascades to its
 * comments (FK on [DiaryCommentEntity]).
 */
@Entity(
    tableName = "diary_entries",
    indices = [Index("timestamp")],
)
data class DiaryEntryEntity(
    @PrimaryKey val uuid: String,
    val content: String = "",
    val timestamp: Long = System.currentTimeMillis(),

    /** JSON list of absolute image file paths (see `DiaryEntryEntity.imagePaths`). "" = none. */
    val imagePathsJson: String = "",

    val moodEmoji: String? = null,
    val moodText: String? = null,

    val isAutoGenerated: Boolean = false,
    val isDraft: Boolean = false,

    val isPetDiary: Boolean = false,
    val petSpeciesRaw: String? = null,

    val visibilityRaw: String = "openToAI",
    val triggerTypeRaw: String = "auto_draft",
    val relatedGiftId: String? = null,

    /**
     * 交换日记（日记重设计 R4·契约 §2 F1）：非 null = 该篇是**角色写的日记**（作者角色 uuid），
     * null = 用户日记。⚠️ 既有「今日去重/补昨/宠物」等 DAO 谓词在 R4 接线时须补 `authorCharacterUuid IS NULL`
     * 守卫（列先随 v22 建好·未写入前不影响任何谓词）。
     */
    val authorCharacterUuid: String? = null,

    /**
     * 作者名快照（日记重设计 R6-3①·孤儿信语义 A「人走信留」）：写交换日记时落下作者当时的名字。
     * 角色**被删后** [authorCharacterUuid] 查不到角色 → UI 用此快照名 + 「故人来信」淡标显示（呈现层归 §6.2 U3）。
     * null = 用户日记，或 v25 前的历史交换日记未回填到（迁移已尽量从 characters 回填存量）。
     */
    val authorNameSnapshot: String? = null,

    /**
     * 交换日记回流消化标记（记忆改造一期·日记回流·图纸 §3.5-C）：非 null = 该交换日记（信件摘录 + 用户回应）
     * 已由消化作业熔入长期记忆；null = 未消化。仅对交换日记（[authorCharacterUuid] 非 null）有意义。
     */
    val digestedAtMillis: Long? = null,
)
