package com.situ.aichat.data.repository

import com.situ.aichat.data.local.dao.DiaryDao
import com.situ.aichat.data.local.entity.DiaryCommentEntity
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.local.entity.DiaryEntryWithComments
import com.situ.aichat.data.local.entity.DiaryReactionEntity
import com.situ.aichat.data.local.entity.MonthlyReviewEntity
import com.situ.aichat.data.model.imagePaths
import com.situ.aichat.util.ContentImageStore
import kotlinx.coroutines.flow.Flow
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Diary aggregate read/write (M07), mirroring how iOS persists `DiaryEntry` + its `DiaryComment`s.
 * Deleting an entry cascades to comments (FK) and additionally cleans up the entry's image files on
 * disk (iOS lets external storage GC the `[Data]`; the Android port stores paths, so it deletes
 * explicitly).
 *
 * Day/month range computation lives in callers (they hold the `ZoneId`); this layer takes raw epoch
 * bounds, keeping the DAO portable.
 */
@Singleton
class DiaryRepository @Inject constructor(
    private val dao: DiaryDao,
) {
    // ---- Reads ----

    fun observeAllWithComments(): Flow<List<DiaryEntryWithComments>> = dao.observeAllWithComments()
    fun observeEntryWithComments(uuid: String): Flow<DiaryEntryWithComments?> = dao.observeEntryWithComments(uuid)
    suspend fun getEntry(uuid: String): DiaryEntryEntity? = dao.getEntry(uuid)
    suspend fun getEntryWithComments(uuid: String): DiaryEntryWithComments? = dao.getEntryWithComments(uuid)

    /** Entries with a timestamp in `[start, end)` (with comments) — selected calendar day. */
    suspend fun entriesInRangeWithComments(start: Long, end: Long): List<DiaryEntryWithComments> =
        dao.entriesInRangeWithComments(start, end)

    /** Plain entries in `[start, end)` — calendar month dots. */
    suspend fun entriesInRange(start: Long, end: Long): List<DiaryEntryEntity> =
        dao.entriesInRange(start, end)

    // ---- Generation-support (consumed by M07 7.1.2) ----

    /** True if today already has an auto-generated (non-pet) diary — the once-per-day dedup. */
    suspend fun hasAutoGeneratedToday(startOfDay: Long): Boolean =
        dao.countAutoGeneratedSince(startOfDay) > 0

    /** True if any diary entry (manual or auto) exists in `[start, end)` — yesterday-backfill dedup. */
    suspend fun hasAnyEntryInRange(start: Long, end: Long): Boolean =
        dao.countInRange(start, end) > 0

    suspend fun lastGiftDiaryTimestamp(): Long? = dao.lastGiftDiaryTimestamp()

    // ---- 交换日记（R4） ----

    /** 该日的交换日记（角色写的·每日至多一篇）；null = 尚未解锁生成。 */
    suspend fun exchangeEntryInRange(start: Long, end: Long): DiaryEntryEntity? =
        dao.exchangeEntryInRange(start, end)

    /** 交换解锁门：该日用户是否已发布（非草稿·非宠物）日记。 */
    suspend fun hasPublishedUserDiaryInRange(start: Long, end: Long): Boolean =
        dao.countPublishedUserDiariesInRange(start, end) > 0

    /** True if today already has a pet diary — the pet-diary once-per-day dedup (P8.2). */
    suspend fun hasPetDiaryToday(startOfDay: Long): Boolean =
        dao.countPetDiariesSince(startOfDay) > 0

    // ---- Writes ----

    suspend fun upsert(entry: DiaryEntryEntity) = dao.upsertEntry(entry)

    /** Delete an entry, its comments (FK cascade), and its image files. */
    suspend fun delete(uuid: String) {
        val entry = dao.getEntry(uuid)
        dao.deleteEntry(uuid)
        entry?.let { ContentImageStore.delete(it.imagePaths) }
    }

    // ---- Comments ----

    suspend fun commentsForEntry(entryUuid: String): List<DiaryCommentEntity> = dao.commentsForEntry(entryUuid)

    /**
     * Insert a comment; generates the row id (iOS comments have no uuid).
     * R3 回复线程：[parentCommentId] 非 null = 某根评论下的回复；[isFromUser]=true = 用户写的回复。
     */
    suspend fun addComment(
        entryUuid: String,
        content: String,
        characterUuid: String?,
        timestamp: Long,
        parentCommentId: String? = null,
        isFromUser: Boolean = false,
    ): DiaryCommentEntity {
        val comment = DiaryCommentEntity(
            id = UUID.randomUUID().toString(),
            entryUuid = entryUuid,
            content = content,
            timestamp = timestamp,
            characterUuid = characterUuid,
            parentCommentId = parentCommentId,
            isFromUser = isFromUser,
        )
        dao.insertComment(comment)
        return comment
    }

    suspend fun deleteComment(id: String) = dao.deleteComment(id)

    suspend fun commentCountByCharacter(entryUuid: String, characterUuid: String): Int =
        dao.commentCountByCharacter(entryUuid, characterUuid)

    // ---- 月度回顾（R5） ----

    /** 落一篇月度回顾（同月已有 → 唯一索引 IGNORE 幂等）。 */
    suspend fun insertMonthlyReview(review: MonthlyReviewEntity) = dao.insertMonthlyReview(review)

    suspend fun monthlyReviewFor(monthStartMillis: Long): MonthlyReviewEntity? =
        dao.monthlyReviewFor(monthStartMillis)

    fun observeMonthlyReviews(): Flow<List<MonthlyReviewEntity>> = dao.observeMonthlyReviews()

    // ---- Reactions（R3 角色点赞） ----

    /** 落一条角色点赞；同角色同条目唯一索引 + IGNORE 天然防重（worker 重试安全）。 */
    suspend fun addReaction(entryUuid: String, characterUuid: String, emoji: String) {
        dao.insertReaction(
            DiaryReactionEntity(
                id = UUID.randomUUID().toString(),
                entryUuid = entryUuid,
                characterUuid = characterUuid,
                emoji = emoji,
                timestamp = System.currentTimeMillis(),
            ),
        )
    }
}
