package com.situ.aichat.prompt.diary

import com.situ.aichat.data.local.dao.CharacterDao
import com.situ.aichat.data.local.dao.MessageDao
import com.situ.aichat.data.local.entity.DiaryEntryEntity
import com.situ.aichat.data.local.entity.MessageEntity
import com.situ.aichat.data.model.AppSettings
import com.situ.aichat.data.repository.DiaryRepository
import com.situ.aichat.data.repository.SettingsRepository
import com.situ.aichat.gift.GiftMomentQueueService
import com.situ.aichat.pet.PetShopMomentQueueService
import com.situ.aichat.prompt.schedule.CharacterSleepChecker
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.mockk
import io.mockk.slot
import io.mockk.verify
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import java.time.Instant
import java.time.ZoneId
import org.junit.Test

/**
 * 纯时间判定（对齐 iOS `DiaryGenerationActor.checkAndAutoGenerate` 的时间门 + `backfillYesterdayDiary` 的 backfillNow）
 * + R2 心情闭环 / R3 自动直发落库接线 T2（补昨路径·无时间闸·确定性）。
 */
class DiaryGenerationCoordinatorTest {

    private val zone: ZoneId = ZoneId.of("UTC")

    /** 补昨路径 T2 夹具：全依赖 MockK 假掉，[arrange] 摆好「昨天无日记 + 有聊天 + 无礼物/宠物分支」的最短通路。 */
    private class BackfillFixture {
        val diaryRepository = mockk<DiaryRepository>()
        val messageDao = mockk<MessageDao>()
        val settingsRepo = mockk<SettingsRepository>()
        val service = mockk<DiaryGenerationService>()
        val giftQueue = mockk<GiftMomentQueueService>()
        val petShopQueue = mockk<PetShopMomentQueueService>()
        val commentService = mockk<DiaryCommentService>(relaxed = true)
        val saved = slot<DiaryEntryEntity>()
        val coordinator = DiaryGenerationCoordinator(
            diaryRepository = diaryRepository,
            characterDao = mockk<CharacterDao>(relaxed = true),
            messageDao = messageDao,
            settingsRepo = settingsRepo,
            sleepChecker = mockk<CharacterSleepChecker>(relaxed = true),
            service = service,
            giftQueue = giftQueue,
            petShopQueue = petShopQueue,
            commentService = commentService,
            monthlyReviewService = mockk<MonthlyReviewService>(relaxed = true),
        )

        fun arrange(settings: AppSettings, draft: DiaryDraft?) {
            coEvery { settingsRepo.getAppSettings() } returns settings
            coEvery { diaryRepository.hasAnyEntryInRange(any(), any()) } returns false
            coEvery { messageDao.messagesInRange(any(), any(), any()) } returns listOf(mockk<MessageEntity>())
            coEvery { giftQueue.resolveGiftBranchForDiary(any()) } returns null
            coEvery { petShopQueue.resolveDiaryBranch(any()) } returns null
            // 5 个 any()：generateDraft(dateMillis, zone, giftInspiration, moodHint, guide)——U2① 加 guide 后同步 arity。
            coEvery { service.generateDraft(any(), any(), any(), any(), any()) } returns draft
            coEvery { diaryRepository.upsert(capture(saved)) } returns Unit
        }
    }

    // MARK: - R2 T2：补昨路径把 DiaryDraft 的推断心情随正文一起落库

    @Test fun `backfillYesterday persists inferred mood from draft`(): Unit = runBlocking {
        val f = BackfillFixture()
        f.arrange(AppSettings(diaryAutoGenerateEnabled = true), DiaryDraft("昨天的正文", "😌"))

        f.coordinator.backfillYesterday()

        coVerify(exactly = 1) { f.diaryRepository.upsert(any()) }
        assertEquals("昨天的正文", f.saved.captured.content)
        assertEquals("😌", f.saved.captured.moodEmoji)  // R2：推断心情随正文落库
        assertNull(f.saved.captured.moodText)            // 标签留 null（UI 资源事务）
        assertTrue(f.saved.captured.isAutoGenerated)
        // R3：直发默认关 → 仍是草稿，且绝不调度评论
        assertTrue(f.saved.captured.isDraft)
        verify(exactly = 0) { f.commentService.scheduleComments(any(), any()) }
    }

    @Test fun `backfillYesterday skips persistence when generation fails`(): Unit = runBlocking {
        val f = BackfillFixture()
        f.arrange(AppSettings(diaryAutoGenerateEnabled = true), draft = null)

        f.coordinator.backfillYesterday()

        coVerify(exactly = 0) { f.diaryRepository.upsert(any()) }
        verify(exactly = 0) { f.commentService.scheduleComments(any(), any()) }
    }

    // MARK: - R3 T2：自动直发（O3 锁定·默认关）

    @Test fun `auto publish on - entry lands published and comments are scheduled`(): Unit = runBlocking {
        val f = BackfillFixture()
        f.arrange(
            AppSettings(diaryAutoGenerateEnabled = true, diaryAutoPublishEnabled = true, diaryCommentDelay = 7),
            DiaryDraft("直发的正文", "😊"),
        )

        f.coordinator.backfillYesterday()

        assertFalse("直发开启 → 落库即已发布（非草稿）", f.saved.captured.isDraft)
        assertEquals("openToAI", f.saved.captured.visibilityRaw)
        verify(exactly = 1) { f.commentService.scheduleComments(f.saved.captured.uuid, 7) }
    }

    @Test fun `parseHourMinute accepts valid HH mm`() {
        assertEquals(21 to 0, DiaryGenerationCoordinator.parseHourMinute("21:00"))
        assertEquals(9 to 5, DiaryGenerationCoordinator.parseHourMinute("9:5"))
        assertEquals(0 to 0, DiaryGenerationCoordinator.parseHourMinute("0:0"))
        assertEquals(23 to 59, DiaryGenerationCoordinator.parseHourMinute("23:59"))
        assertEquals(7 to 30, DiaryGenerationCoordinator.parseHourMinute(" 7 : 30 ")) // 容空格
    }

    @Test fun `parseHourMinute rejects malformed or out-of-range`() {
        assertNull(DiaryGenerationCoordinator.parseHourMinute("21"))        // 仅一段
        assertNull(DiaryGenerationCoordinator.parseHourMinute("21:00:00"))  // 三段（iOS count==2 守卫）
        assertNull(DiaryGenerationCoordinator.parseHourMinute("ab:cd"))     // 非数字
        assertNull(DiaryGenerationCoordinator.parseHourMinute("21:ab"))
        assertNull(DiaryGenerationCoordinator.parseHourMinute("24:00"))     // 小时越界
        assertNull(DiaryGenerationCoordinator.parseHourMinute("21:60"))     // 分钟越界
        assertNull(DiaryGenerationCoordinator.parseHourMinute(""))
    }

    @Test fun `targetTimeMillis is today at the given hour-minute`() {
        // now = 2023-11-14 22:13:20 UTC（任意当天时刻）
        val now = 1_700_000_000_000L
        val target = DiaryGenerationCoordinator.targetTimeMillis(now, 21, 0, zone)
        val zdt = Instant.ofEpochMilli(target).atZone(zone)
        assertEquals(21, zdt.hour)
        assertEquals(0, zdt.minute)
        assertEquals(0, zdt.second)
        // 与 now 同一日历日
        assertEquals(Instant.ofEpochMilli(now).atZone(zone).toLocalDate(), zdt.toLocalDate())
    }

    @Test fun `backfillTimestamp is yesterday 0am plus 22h`() {
        // 昨天 0 点（UTC）
        val yesterdayStart = Instant.parse("2026-05-30T00:00:00Z").toEpochMilli()
        val ts = DiaryGenerationCoordinator.backfillTimestampMillis(yesterdayStart)
        val zdt = Instant.ofEpochMilli(ts).atZone(zone)
        assertEquals(22, zdt.hour)
        assertEquals(0, zdt.minute)
        assertEquals(yesterdayStart + 22L * 60 * 60 * 1000, ts)
    }
}
